-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.booking_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  role text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT booking_contacts_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_contacts_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.booking_slots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid,
  branch_id uuid,
  slot_start timestamp with time zone NOT NULL,
  slot_end timestamp with time zone NOT NULL,
  participants_count integer NOT NULL DEFAULT 1,
  slot_type text NOT NULL DEFAULT 'game_zone'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_slots_pkey PRIMARY KEY (id),
  CONSTRAINT booking_slots_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_slots_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['GAME'::text, 'EVENT'::text])),
  status text NOT NULL DEFAULT 'CONFIRMED'::text CHECK (status = ANY (ARRAY['DRAFT'::text, 'CONFIRMED'::text, 'CANCELLED'::text])),
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  game_start_datetime timestamp with time zone,
  game_end_datetime timestamp with time zone,
  participants_count integer NOT NULL DEFAULT 1,
  event_room_id uuid,
  customer_first_name text NOT NULL,
  customer_last_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  customer_notes_at_booking text,
  reference_code text NOT NULL UNIQUE,
  total_price numeric,
  notes text,
  color text,
  primary_contact_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT bookings_event_room_id_fkey FOREIGN KEY (event_room_id) REFERENCES public.event_rooms(id),
  CONSTRAINT bookings_primary_contact_id_fkey FOREIGN KEY (primary_contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.branch_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid,
  max_concurrent_players integer NOT NULL DEFAULT 84,
  slot_duration_minutes integer NOT NULL DEFAULT 15,
  game_duration_minutes integer NOT NULL DEFAULT 60,
  event_total_duration_minutes integer NOT NULL DEFAULT 120,
  event_game_duration_minutes integer NOT NULL DEFAULT 60,
  event_buffer_before_minutes integer NOT NULL DEFAULT 15,
  event_buffer_after_minutes integer NOT NULL DEFAULT 15,
  event_min_participants integer NOT NULL DEFAULT 1,
  game_price_per_person numeric NOT NULL DEFAULT 0,
  bracelet_price numeric NOT NULL DEFAULT 0,
  event_price_15_29 numeric NOT NULL DEFAULT 0,
  event_price_30_plus numeric NOT NULL DEFAULT 0,
  opening_hours jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  total_slots integer DEFAULT 14 CHECK (total_slots > 0),
  max_players_per_slot integer DEFAULT 6 CHECK (max_players_per_slot > 0),
  laser_total_vests integer DEFAULT 0,
  laser_enabled boolean DEFAULT false,
  CONSTRAINT branch_settings_pkey PRIMARY KEY (id),
  CONSTRAINT branch_settings_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  name_en text,
  address text NOT NULL,
  phone text,
  phone_extension text,
  timezone text NOT NULL DEFAULT 'Europe/Paris'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT branches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id_main uuid NOT NULL,
  first_name text NOT NULL,
  last_name text,
  phone text NOT NULL,
  email text,
  notes_client text,
  alias text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'archived'::text])),
  source text DEFAULT 'admin_agenda'::text CHECK (source = ANY (ARRAY['admin_agenda'::text, 'public_booking'::text, 'website'::text])),
  archived_at timestamp with time zone,
  archived_reason text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT contacts_branch_id_main_fkey FOREIGN KEY (branch_id_main) REFERENCES public.branches(id),
  CONSTRAINT contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.event_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid,
  slug text NOT NULL,
  name text NOT NULL,
  name_en text,
  capacity integer NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT event_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT event_rooms_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.game_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  game_area text NOT NULL CHECK (game_area = ANY (ARRAY['ACTIVE'::text, 'LASER'::text])),
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  laser_room_id uuid,
  session_order integer NOT NULL DEFAULT 1,
  pause_before_minutes integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT game_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT game_sessions_laser_room_id_fkey FOREIGN KEY (laser_room_id) REFERENCES public.laser_rooms(id),
  CONSTRAINT game_sessions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.laser_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid,
  slug text NOT NULL,
  name text NOT NULL,
  name_en text,
  capacity integer NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT laser_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT laser_rooms_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid,
  order_type character varying NOT NULL CHECK (order_type::text = ANY (ARRAY['GAME'::character varying, 'EVENT'::character varying]::text[])),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::order_status,
  booking_id uuid,
  contact_id uuid,
  request_reference character varying NOT NULL UNIQUE,
  customer_first_name character varying NOT NULL,
  customer_last_name character varying,
  customer_phone character varying NOT NULL,
  customer_email character varying,
  customer_notes text,
  requested_date date NOT NULL,
  requested_time time without time zone NOT NULL,
  participants_count integer NOT NULL CHECK (participants_count > 0),
  game_area character varying CHECK (game_area::text = ANY (ARRAY['ACTIVE'::character varying, 'LASER'::character varying, NULL::character varying]::text[])),
  number_of_games integer DEFAULT 1,
  event_type character varying,
  event_celebrant_age integer,
  pending_reason USER-DEFINED,
  pending_details text,
  terms_accepted boolean NOT NULL DEFAULT false,
  terms_accepted_at timestamp with time zone,
  processed_at timestamp with time zone,
  processed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source text DEFAULT 'website'::text,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT orders_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT orders_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT orders_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role text NOT NULL DEFAULT 'agent'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'branch_admin'::text, 'agent'::text])),
  full_name text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  first_name character varying,
  last_name character varying,
  phone character varying,
  created_by uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_branches_pkey PRIMARY KEY (id),
  CONSTRAINT user_branches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_branches_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);