openapi: 3.1.0
info:
  version: '1.0'
  title: Currency information
servers:
  - url: 'https://api.icount.co.il/api/v3.php/currency'
    description: ''
paths:
  /today:
    post:
      summary: Get currency exchange rate for today
      operationId: post-today
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                currency_id:
                  $ref: '#/components/schemas/CurrencyID'
                currency_code:
                  $ref: '#/components/schemas/CurrencyCode'
                currency:
                  description: 'Currency identifier (either ID, or Code, or name)'
                  oneOf:
                    - type: string
                    - type: integer
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/currency'
          description: ''
  /by_date:
    post:
      summary: Get currency exchange rate for given date
      operationId: post-by_date
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                currency_id:
                  $ref: '#/components/schemas/CurrencyID'
                currency_code:
                  $ref: '#/components/schemas/CurrencyCode'
                currency:
                  description: 'Currency identifier (either ID, or Code, or name)'
                  oneOf:
                    - type: string
                    - type: integer
                date:
                  type: string
                  description: Date in format YYYY-MM-DD
                  format: date
              required:
                - date
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/currency'
          description: ''
  /info:
    post:
      summary: Get currency information
      operationId: post-info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                currency_id:
                  $ref: '#/components/schemas/CurrencyID'
                currency_code:
                  $ref: '#/components/schemas/CurrencyCode'
                currency:
                  description: 'Currency identifier (either ID, or Code, or name)'
                  oneOf:
                    - type: string
                    - type: integer
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/currency'
          description: ''
  /get_rates:
    post:
      summary: Get currencies rates (latest)
      operationId: post-get_rates
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/currency'
          description: ''
  /get_rates_by_date:
    post:
      summary: Get currencies rates by date
      operationId: post-get_rates_by_date
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                date:
                  type: string
                  description: Date in format YYYY-MM-DD
                  format: date
              required:
                - date
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/currency'
          description: ''
  /get_list:
    post:
      summary: Get currencies list
      operationId: post-get_list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                list_type:
                  type: string
                  description: List type (array|object).
                get_rates:
                  type: boolean
                  description: get current exchange rates as well
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/currency'
          description: ''
components:
  schemas:
    CurrencyID:
      type: object
      title: CurrencyID
      description: Currency ID
      properties:
        Base type:
          type: integer
    CurrencyCode:
      type: object
      title: CurrencyCode
      description: Currency Code (3-letter code defined by ISO-4217)
      properties:
        Base type:
          type: string
