openapi: 3.1.0
info:
  version: '1.0'
  title: Customer status management
servers:
  - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
    description: ''
paths:
  /get_list:
    post:
      summary: Get client status list
      operationId: post-get_list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                list_type:
                  type: string
                  description: Result list type (array/object).
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
          description: ''
  /info:
    post:
      summary: Get client status info
      operationId: post-info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                client_status_id:
                  type: integer
                  description: Client status ID
              required:
                - client_status_id
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
          description: ''
  /add:
    post:
      summary: Add client status
      operationId: post-add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                status_name:
                  type: string
                  description: Client status name
                status_description:
                  type: string
                  description: Client status description
                is_milestone:
                  type: boolean
                  description: Is this status a milestone?
              required:
                - status_name
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
          description: ''
  /update:
    post:
      summary: Update client status information
      operationId: post-update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                client_status_id:
                  type: integer
                  description: Client status ID
                status_name:
                  type: string
                  description: Client status name
                status_description:
                  type: string
                  description: Client status description
                is_milestone:
                  type: boolean
                  description: Is this status a milestone?
              required:
                - client_status_id
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
          description: ''
  /delete:
    post:
      summary: Delete client status
      operationId: post-delete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                client_status_id:
                  type: integer
                  description: Client status ID
                force:
                  type: boolean
                  description: Force deletion of status even if it has clients assigned
              required:
                - client_status_id
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
          description: ''
  /reorder:
    post:
      summary: Reorder client status list
      operationId: post-reorder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                client_status_order:
                  type: array
                  description: List of client_status_ids in desired order
              required:
                - client_status_order
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/crm_client_status'
          description: ''
