openapi: 3.1.0
info:
  version: '1.0'
  title: System notifications
servers:
  - url: 'https://api.icount.co.il/api/v3.php/system_notification'
paths:
  /get_list:
    post:
      summary: Get notifications list
      operationId: post-get_list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                limit:
                  type: integer
                  description: Limit amount of returned notifications.
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/system_notification'
  /seen:
    post:
      summary: Mark notifications as seen
      operationId: post-seen
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                notification_ids:
                  type: array
                  description: List of notification IDs
                  items:
                    type: integer
              required:
                - notification_ids
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/system_notification'
  /dismiss:
    post:
      summary: Dismiss notifications
      operationId: post-dismiss
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                notification_ids:
                  type: array
                  description: List of notification IDs
                  items:
                    type: integer
              required:
                - notification_ids
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/system_notification'
  /archive:
    post:
      summary: Archive notifications
      operationId: post-archive
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                notification_ids:
                  type: array
                  description: List of notification IDs
                  items:
                    type: integer
              required:
                - notification_ids
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/system_notification'
  /unarchive:
    post:
      summary: Unarchive notifications
      operationId: post-unarchive
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                notification_ids:
                  type: array
                  description: List of notification IDs
                  items:
                    type: integer
              required:
                - notification_ids
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/system_notification'
  /delete:
    post:
      summary: Delete notifications
      operationId: post-delete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                notification_ids:
                  type: array
                  description: List of notification IDs
                  items:
                    type: integer
              required:
                - notification_ids
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/system_notification'
