openapi: 3.1.0
info:
  version: '1.0'
  title: Tags management
servers:
  - url: 'https://api.icount.co.il/api/v3.php/tag'
paths:
  /info:
    post:
      summary: Get tag info
      operationId: post-info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                tag_id:
                  type: integer
                  description: Tag ID
              required:
                - tag_id
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/tag'
  /add:
    post:
      summary: Add new tag
      operationId: post-add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                tag_name:
                  type: string
                  description: Tag name
              required:
                - tag_name
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/tag'
  /update:
    post:
      summary: Update tag
      operationId: post-update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                tag_id:
                  type: integer
                  description: Tag ID
                tag_name:
                  type: string
                  description: Tag name
              required:
                - tag_id
                - tag_name
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/tag'
  /delete:
    post:
      summary: Delete tag
      operationId: post-delete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                tag_id:
                  type: integer
                  description: Tag ID
              required:
                - tag_id
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/tag'
  /get_list:
    post:
      summary: Get tags list
      operationId: post-get_list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
                list_type:
                  type: array
                  description: List type (array|object).
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/tag'
