openapi: 3.1.0
info:
  version: '1.0'
  title: VAT (Value Added Tax)
servers:
  - url: 'https://api.icount.co.il/api/v3.php/vat'
paths:
  /today:
    post:
      summary: Get current VAT percent
      operationId: post-today
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/vat'
  /by_date:
    post:
      summary: Get VAT percent by date
      operationId: post-by_date
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sid:
                  type: string
                  description: Session ID
                cid:
                  type: string
                  description: Company identifier
                user:
                  type: string
                  description: Username
                pass:
                  type: string
                  description: Password
      responses:
        '200':
          description: OK
      servers:
        - url: 'https://api.icount.co.il/api/v3.php/vat'
